server:
  port: 8761

spring:
  application:
    name: discovery-service
  security:
    user:
      name: admin
      password: password123

eureka:
  instance:

    hostname: ${EUREKA_HOSTNAME:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/